/*
 * Copyright 2026 Bad Monkey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Cross-language golden tests: the same golden.json the Python client proves
 * itself against (generated by tools/golden/GoldenVectors.java from the Java
 * codec), now proven byte for byte from TypeScript. Ed25519 signing is
 * deterministic (RFC 8032), so signatures must match exactly too.
 */

import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { CborDouble, dumps, loads } from "../src/cbor.js";
import {
  Identity,
  certificateBody,
  deriveId,
  foundGroup,
  foundingDocument,
  foundingFields,
  foundingFieldsOf,
  groupIdFromFounding,
  groupIdFromFoundingDocument,
  parseDurationMillis,
  parseInstantMillis,
  spaceIdLocal,
  verifyAgentCertificate,
  verifyAgentCertificateAt,
  verifySignedGroupAd,
} from "../src/identity.js";
import { Peer, joinStates } from "../src/peer.js";
import * as vote from "../src/vote.js";
import * as revocation from "../src/revocation.js";
import * as wire from "../src/wire.js";
import type { Dict } from "../src/wire.js";

const here = dirname(fileURLToPath(import.meta.url));
const GOLDEN: { [key: string]: string } = JSON.parse(readFileSync(
  join(here, "..", "..", "test", "golden.json"), "utf-8"));

function hex(name: string): Buffer {
  return Buffer.from(GOLDEN[name], "hex");
}

function identity(): Identity {
  return Identity.fromPkcs8(hex("private_key_pkcs8"));
}

test("identity and derivations match Java", () => {
  const id = identity();
  assert.deepEqual(Buffer.from(id.publicRaw), hex("public_key_raw"));
  assert.equal(id.peerId, GOLDEN["peer_id"]);
  assert.equal(deriveId(hex("public_key_raw")), GOLDEN["peer_id"]);
  assert.equal(groupIdFromFounding("research-fleet-demo-v1"), GOLDEN["group_id"]);
  assert.equal(spaceIdLocal(GOLDEN["group_id"] + "/tasks"), GOLDEN["space_id"]);
});

test("ping envelope bytes and signature match Java", () => {
  const id = identity();
  assert.deepEqual(wire.pingBody(42), hex("ping_body_cbor"));
  const env = wire.envelope(GOLDEN["group_id"], "PING", GOLDEN["peer_id"],
    GOLDEN["hlc_encoded"], hex("ping_body_cbor"), GOLDEN["peer_id"]);
  assert.deepEqual(dumps(env), hex("ping_envelope_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(env))),
    hex("ping_envelope_signature"));
  assert.deepEqual(wire.encodeFrame(env, id), hex("ping_frame_cbor"));
});

test("TypeScript verifies and rejects Java frames correctly", () => {
  const env = wire.decodeFrame(hex("ping_frame_cbor"));
  assert.ok(env);
  assert.equal(env["kind"], "PING");
  assert.equal(env["from"], GOLDEN["peer_id"]);
  const tampered = Buffer.from(hex("ping_frame_cbor"));
  tampered[tampered.length - 1] ^= 0x01;
  assert.equal(wire.decodeFrame(tampered), null);
});

test("membership intro matches Java", () => {
  const id = identity();
  const ad = wire.peerAdvertisement(GOLDEN["group_id"], id, "2026-01-01T00:00:00Z");
  ad["endpoints"] = [{ transport: "tcp", address: "127.0.0.1:7460", priority: 0 }];
  assert.deepEqual(dumps(ad), hex("peer_ad_cbor"));
  assert.deepEqual(wire.signedPeerAd(ad, id), hex("signed_peer_ad_cbor"));
  const itemId = `peer:${id.peerId}:1767225600000`;
  assert.deepEqual(wire.rumorBody("peers", itemId, 6, hex("signed_peer_ad_cbor")),
    hex("intro_rumor_body_cbor"));
});

test("space write matches Java", () => {
  const id = identity();
  const payload = dumps({ topic: "golden vectors", priority: 3 });
  assert.deepEqual(payload, hex("task_payload_cbor"));

  const view = wire.signView("11111111-2222-3333-4444-555555555555",
    GOLDEN["space_id"], "GoldenVectors$ResearchTask#v1", payload,
    id.agent("python"), GOLDEN["hlc_encoded"]);
  assert.deepEqual(dumps(view), hex("sign_view_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(view))), hex("record_signature"));

  const lease: Dict = { holder: id.agent("python"),
    expiresAtMillis: 1735693200000, kind: "WRITE" };
  const record: Dict = {
    entryId: "11111111-2222-3333-4444-555555555555",
    spaceId: GOLDEN["space_id"],
    type: "GoldenVectors$ResearchTask#v1",
    payload, payloadRef: null,
    issuer: id.agent("python"),
    issued: GOLDEN["hlc_encoded"],
    lease, tags: {}, sig: hex("record_signature"),
  };
  const adds = [{ replica: id.peerId, counter: 1 }];
  const leaseValue: Dict = { holder: id.agent("python"),
    expiresAtMillis: 1735693200000, kind: "WRITE" };
  const stateView = wire.stateSignView(GOLDEN["space_id"],
    "11111111-2222-3333-4444-555555555555", adds, [], GOLDEN["hlc_encoded"],
    leaseValue, false);
  assert.deepEqual(dumps(stateView), hex("state_sign_view_cbor"));
  const stateSig = Buffer.from(id.sign(dumps(stateView)));
  assert.deepEqual(stateSig, hex("state_signature"));

  const dto: Dict = {
    record, issuerPublicKey: id.publicRaw,
    adds, removes: [], leaseStamp: GOLDEN["hlc_encoded"],
    leaseValue, completed: false, stateSig,
  };
  assert.deepEqual(dumps(dto), hex("entry_state_dto_cbor"));
  assert.deepEqual(dumps({ state: dto, claimEntry: null, claim: null }),
    hex("delta_cbor"));
});

test("subordinate agent certificate and agent-signed record match Java (SPEC 4.2, 11a.3)", () => {
  // QA4 A4-7 phase 1: the peer certifies an agent key; the agent key signs
  // the record; the DTO carries both.
  const id = identity();
  const issued = GOLDEN["certificate_verify_at"];
  const agent = id.subordinate("python", issued, "PT24H",
    Identity.fromPkcs8(hex("agent_private_key_pkcs8")));
  assert.equal(agent.agentId, id.agent("python"));
  assert.deepEqual(Buffer.from(agent.publicRaw), hex("agent_public_key_raw"));
  assert.deepEqual(dumps(certificateBody(agent.certificate)), hex("agent_certificate_unsigned_cbor"));
  assert.deepEqual(Buffer.from(agent.certificate["peerSignature"] as Uint8Array),
    hex("agent_certificate_signature"));
  assert.deepEqual(dumps(agent.certificate), hex("agent_certificate_cbor"));
  const nowMillis = parseInstantMillis(issued);
  assert.equal(verifyAgentCertificate(loads(hex("agent_certificate_cbor")), id.publicRaw,
    id.agent("python"), nowMillis), true);
  // Expiry is inclusive: issued + ttl is the first refused instant.
  assert.equal(verifyAgentCertificate(agent.certificate, id.publicRaw, id.agent("python"),
    nowMillis + parseDurationMillis("PT24H") - 1), true);
  assert.equal(verifyAgentCertificate(agent.certificate, id.publicRaw, id.agent("python"),
    nowMillis + parseDurationMillis("PT24H")), false);

  const view = hex("sign_view_cbor");
  const sig = agent.sign(view);
  assert.deepEqual(Buffer.from(sig), hex("record_signature_agent_key"));
  assert.equal(Identity.verify(agent.publicRaw, view, sig), true);
  assert.equal(Identity.verify(id.publicRaw, view, sig), false); // not the peer's

  const leaseValue = { holder: id.agent("python"), expiresAtMillis: 1735693200000, kind: "WRITE" };
  const record: Dict = {
    entryId: "11111111-2222-3333-4444-555555555555", spaceId: GOLDEN["space_id"],
    type: "GoldenVectors$ResearchTask#v1", payload: hex("task_payload_cbor"),
    payloadRef: null, issuer: id.agent("python"), issued: GOLDEN["hlc_encoded"],
    lease: leaseValue, tags: {}, sig,
  };
  const dto: Dict = {
    record, issuerPublicKey: id.publicRaw,
    adds: [{ replica: id.peerId, counter: 1 }], removes: [],
    leaseStamp: GOLDEN["hlc_encoded"], leaseValue, completed: false,
    stateSig: hex("state_signature"), agentCertificate: agent.certificate,
  };
  assert.deepEqual(dumps(dto), hex("entry_state_with_certificate_cbor"));
  assert.deepEqual(dumps({ state: dto, claimEntry: null, claim: null }),
    hex("delta_with_certificate_cbor"));
  assert.equal(wire.verifyRecord(record, id.publicRaw, agent.certificate, nowMillis), true);

  // SPEC §11a.4 v0.1.13 (A6): that state is peer-signed on an agent-attested
  // entry and is refused; the agent-signed state is what lands.
  const peer = new Peer(id, GOLDEN["group_id"], () => nowMillis);
  const fold = (name: string) => (peer as unknown as { fold(dto: Dict): void })
    .fold((loads(hex(name)) as Dict)["state"] as Dict);
  fold("delta_with_certificate_cbor");
  assert.equal(peer.states.size, 0);
  const signer = id.agent("python");
  const signedAt = GOLDEN["hlc_encoded"];
  const stateView = wire.stateSignView(GOLDEN["space_id"], String(record["entryId"]),
    dto["adds"] as Dict[], [], signedAt, leaseValue, false, signer, signedAt);
  assert.deepEqual(dumps(stateView), hex("state_sign_view_agent_cbor"));
  const agentStateSig = agent.sign(dumps(stateView));
  assert.deepEqual(Buffer.from(agentStateSig), hex("state_signature_agent_key"));
  const agentDto: Dict = { record, issuerPublicKey: id.publicRaw, adds: dto["adds"], removes: [],
    leaseStamp: signedAt, leaseValue, completed: false, stateSig: agentStateSig,
    agentCertificate: agent.certificate, stateCertificate: agent.certificate, signer, signedAt };
  assert.deepEqual(dumps(agentDto), hex("entry_state_agent_signed_cbor"));
  assert.deepEqual(dumps({ state: agentDto, claimEntry: null, claim: null }),
    hex("delta_agent_signed_cbor"));
  fold("delta_agent_signed_cbor");
  fold("delta_cbor");
  assert.deepEqual([...peer.states.keys()], ["11111111-2222-3333-4444-555555555555"]);
});

test("three names from one peer tally as one voter (SPEC 8 QUORUM)", () => {
  // QA4 A4-7 phase 2: the counted identity follows the authorizer's
  // granularity: one voter per peer, and nobody per agent for peer-asserted names.
  const id = identity();
  const peer = new Peer(id, GOLDEN["group_id"],
    () => parseInstantMillis(GOLDEN["certificate_verify_at"]));
  for (const i of [1, 2, 3]) {
    (peer as unknown as { fold(dto: Dict): void })
      .fold((loads(hex(`vote_three_names_one_peer_delta_${i}`)) as Dict)["state"] as Dict);
  }
  assert.equal(peer.states.size, 3);
  const proposal = GOLDEN["vote_three_names_one_peer_proposal"];
  assert.deepEqual([...vote.tally(peer.states, proposal, ["approve", "reject"])],
    [["approve", 1], ["reject", 0]]);
  assert.deepEqual([...vote.tally(peer.states, proposal, ["approve", "reject"], "AGENT")],
    [["approve", 0], ["reject", 0]]);
  assert.equal(vote.tally(peer.states, proposal, null, "PEER", () => false).size, 0);
});

test("take claims match Java, and decoded claims re-encode identically", () => {
  const id = identity();
  const claim = wire.takeClaim("11111111-2222-3333-4444-555555555555",
    GOLDEN["space_id"], 1, GOLDEN["hlc_encoded"], id.agent("python"),
    0.0, 1735693200000);
  assert.deepEqual(dumps(claim), hex("take_claim_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(claim))),
    hex("take_claim_signature"));
  const signed = wire.signedClaim(claim, id);
  assert.deepEqual(wire.claimDelta("11111111-2222-3333-4444-555555555555", signed),
    hex("claim_delta_cbor"));

  // The double survives a decode-encode round trip (the bid stays 0xFB).
  const decoded = loads(hex("take_claim_cbor")) as Dict;
  assert.ok(decoded["bid"] instanceof CborDouble);
  assert.deepEqual(dumps(decoded), hex("take_claim_cbor"));
});

test("agent-signed claims match Java (TECH-SPEC 7.6, QA4 A4-7 phase 3)", () => {
  const id = identity();
  const agent = id.subordinate("python", GOLDEN["certificate_verify_at"], "PT24H",
    Identity.fromPkcs8(hex("agent_private_key_pkcs8")));
  const claim = loads(hex("take_claim_cbor")) as Dict;
  assert.deepEqual(Buffer.from(agent.sign(hex("take_claim_cbor"))), hex("take_claim_agent_signature"));
  const signed = wire.signedClaim(claim, id, agent);
  assert.deepEqual(wire.claimDelta("11111111-2222-3333-4444-555555555555", signed),
    hex("claim_delta_with_certificate_cbor"));
  assert.deepEqual(dumps(wire.signedClaim(claim, id)),
    dumps((loads(hex("claim_delta_cbor")) as Dict)["claim"] as Dict)); // no agent: unchanged
  const nowMillis = parseInstantMillis(GOLDEN["certificate_verify_at"]);
  assert.equal(wire.verifyClaimProof(signed, nowMillis), true);
  assert.equal(wire.verifyClaimProof({ ...signed, holderCertificate: null }, nowMillis), false);
  // The peer folds the certified proof and drops each hostile one.
  const control = peerAt(GOLDEN["certificate_verify_at"]);
  const good = loads(hex("claim_delta_with_certificate_cbor")) as Dict;
  (control as unknown as { foldClaim(e: string, s: Dict): void })
    .foldClaim(String(good["claimEntry"]), good["claim"] as Dict);
  assert.equal(control.claims.size, 1);
  for (const name of ["adv_claim_cert_peer_signed_delta", "adv_claim_cert_expired_delta",
    "adv_claim_cert_wrong_holder_delta"]) {
    const peer = peerAt(GOLDEN["certificate_verify_at"]);
    const delta = loads(hex(name)) as Dict;
    (peer as unknown as { foldClaim(e: string, s: Dict): void })
      .foldClaim(String(delta["claimEntry"]), delta["claim"] as Dict);
    assert.equal(peer.claims.size, 0, name);
  }
});

test("claim lattice order matches the Java merge", () => {
  const e = "entry-1", s = "space-1";
  const base = wire.takeClaim(e, s, 1, "100:0:node-a", "peer/a", 0.0, 1000);
  const higherEpoch = wire.takeClaim(e, s, 2, "200:0:node-b", "peer/b", 0.0, 1000);
  const cheaper = wire.takeClaim(e, s, 1, "200:0:node-b", "peer/b", -1.0, 1000);
  const earlier = wire.takeClaim(e, s, 1, "50:0:node-b", "peer/b", 0.0, 1000);
  const winner = (a: Dict, b: Dict): Dict =>
    wire.mergeClaims({ claim: a }, { claim: b })["claim"] as Dict;
  assert.deepEqual(winner(base, higherEpoch), higherEpoch);
  assert.deepEqual(winner(base, cheaper), cheaper);
  assert.deepEqual(winner(base, earlier), earlier);
});

// ---------------------------------------------------------------------------
// v0.1.10 wire foundation (QA2 workstream C): self-certifying founding,
// join-by-GroupID frames, the extended advertisements, and the capability
// payloads, each reproduced from the golden key and compared byte for byte.

const FOUNDING = {
  name: "golden-fleet", policy: "OPEN", strategy: "LEASE_RACE", fanout: 3,
  period: "PT1S", issued: "2026-01-01T00:00:00Z", ttl: "PT24H",
};

function golden(): Dict {
  return foundGroup(identity(), FOUNDING.name, FOUNDING.policy, FOUNDING.strategy,
    FOUNDING.fanout, FOUNDING.period, FOUNDING.issued, FOUNDING.ttl);
}

test("group founding derives the self-certifying GroupID like Java (SPEC 4.4, 5.1)", () => {
  const id = identity();
  const fields = foundingFields(FOUNDING.name, id.peerId, FOUNDING.issued,
    FOUNDING.ttl, FOUNDING.policy, FOUNDING.strategy, FOUNDING.fanout, FOUNDING.period);
  assert.deepEqual(dumps(fields), hex("founding_fields_cbor"));
  const signature = id.sign(dumps(fields));
  assert.deepEqual(Buffer.from(signature), hex("founding_signature"));
  const document = dumps(foundingDocument(fields, signature));
  assert.deepEqual(document, hex("founding_document_cbor"));
  assert.equal(groupIdFromFoundingDocument(document), GOLDEN["founding_group_id"]);

  const signed = golden();
  const ad = signed["advertisement"] as Dict;
  assert.equal(ad["group"], GOLDEN["founding_group_id"]);
  assert.equal(ad["id"], GOLDEN["founding_ad_id"]);
  assert.deepEqual(dumps(ad), hex("group_ad_cbor"));
  assert.deepEqual(dumps(signed), hex("signed_group_ad_cbor"));
  assert.deepEqual(dumps(foundingFieldsOf(ad)), hex("founding_fields_cbor"));

  // The four checks pass on the genuine document, from the Dict and from bytes.
  assert.equal(verifySignedGroupAd(signed), GOLDEN["founding_group_id"]);
  assert.equal(verifySignedGroupAd(hex("signed_group_ad_cbor")), GOLDEN["founding_group_id"]);
});

test("adversarial GROUP_AD answers fail the four checks (SPEC 5.1)", () => {
  // A genuine founder signature under the wrong GroupID: the founding
  // document still derives to the real group, which is exactly why the
  // advertised group is refused.
  const wrongId = loads(hex("adv_group_ad_wrong_id_cbor")) as Dict;
  assert.equal(verifySignedGroupAd(wrongId), null);
  const wrongAd = wrongId["advertisement"] as Dict;
  assert.equal(wrongAd["group"], GOLDEN["group_id"]);
  assert.equal(groupIdFromFoundingDocument(dumps(foundingDocument(
    foundingFieldsOf(wrongAd), wrongId["signature"] as Uint8Array))),
    GOLDEN["founding_group_id"]);

  // The right group and the golden founder key, signed by someone else.
  const forged = loads(hex("adv_group_ad_forged_signature_cbor")) as Dict;
  assert.equal(verifySignedGroupAd(forged), null);
  assert.equal((forged["advertisement"] as Dict)["group"], GOLDEN["founding_group_id"]);
  const forger = Identity.fromPkcs8(hex("adv_forger_private_key_pkcs8"));
  assert.ok(Identity.verify(forger.publicRaw, hex("founding_fields_cbor"),
    forged["signature"] as Uint8Array), "the forged vector is signed by the forger key");

  // Malformed inputs are refused, never thrown.
  assert.equal(verifySignedGroupAd(null), null);
  assert.equal(verifySignedGroupAd(Buffer.from([0xff])), null);
  assert.equal(verifySignedGroupAd({ advertisement: {}, founderPublicKey: new Uint8Array(32),
    signature: new Uint8Array(64) }), null);
});

test("GROUP_AD_WANT and GROUP_AD frames match Java (SPEC 9, 10.1)", () => {
  const id = identity();
  const group = GOLDEN["founding_group_id"];
  // The vector addresses the request to peer_id to exercise the destination
  // binding; a live request is unaddressed (to = null).
  const want = wire.groupAdWantEnvelope(group, id.peerId, GOLDEN["hlc_encoded"], id.peerId);
  assert.deepEqual(dumps(want), hex("group_ad_want_envelope_cbor"));
  assert.deepEqual(wire.encodeFrame(want, id), hex("group_ad_want_frame_cbor"));
  assert.equal(wire.groupAdWantEnvelope(group, id.peerId, "1:0:x")["to"], null);

  const body = wire.groupAdBody(golden());
  assert.deepEqual(body, hex("signed_group_ad_cbor"));
  const answer = wire.envelope(group, "GROUP_AD", id.peerId, GOLDEN["hlc_encoded"],
    body, id.peerId);
  assert.deepEqual(dumps(answer), hex("group_ad_envelope_cbor"));
  assert.deepEqual(wire.encodeFrame(answer, id), hex("group_ad_frame_cbor"));

  const decodedWant = wire.decodeFrame(hex("group_ad_want_frame_cbor"));
  assert.ok(decodedWant);
  assert.equal(decodedWant["kind"], "GROUP_AD_WANT");
  assert.equal(decodedWant["group"], group);
  assert.deepEqual(Buffer.from(decodedWant["body"] as Uint8Array), Buffer.alloc(0));

  const decodedAnswer = wire.decodeFrame(hex("group_ad_frame_cbor"));
  assert.ok(decodedAnswer);
  assert.equal(decodedAnswer["kind"], "GROUP_AD");
  assert.equal(decodedAnswer["group"], group);
  assert.deepEqual(Buffer.from(decodedAnswer["body"] as Uint8Array),
    hex("signed_group_ad_cbor"));
  assert.equal(verifySignedGroupAd(decodedAnswer["body"] as Uint8Array), group);
});

test("a frame of another wire version is dropped before verification (SPEC 9)", () => {
  assert.equal(wire.WIRE_VERSION, Number(GOLDEN["wire_version"]));
  const id = identity();
  const env = wire.envelope(GOLDEN["group_id"], "PING", id.peerId,
    GOLDEN["hlc_encoded"], wire.pingBody(42), id.peerId);
  assert.equal(env["ver"], 2);
  assert.notEqual(wire.decodeFrame(wire.encodeFrame(env, id)), null);
  const v1 = { ...env, ver: 1 };
  assert.equal(wire.decodeFrame(wire.encodeFrame(v1, id)), null,
    "a validly signed ver=1 frame is refused");
  const v3 = { ...env, ver: 3 };
  assert.equal(wire.decodeFrame(wire.encodeFrame(v3, id)), null);
});

test("AgentCard and SpaceAdvertisement match Java (SPEC 6.1, 4.4)", () => {
  const id = identity();
  const group = GOLDEN["group_id"];
  const card = wire.agentCard(group, id, "python", "2026-01-01T00:00:00Z", "PT15M",
    "Researches a topic and writes a finding", ["research"],
    ["GoldenVectors$ResearchTask#v1"], ["GoldenVectors$Finding#v1"],
    { tokens: "low" }, { "GoldenVectors$ResearchTask#v1": "tasks" });
  assert.equal(card["id"], `aspace://${group}/agent/${id.peerId}/python`);
  assert.deepEqual(dumps(card), hex("agent_card_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(card))), hex("agent_card_signature"));
  assert.deepEqual(dumps(wire.storedAd("AgentCard", card, id)), hex("signed_agent_card_cbor"));
  // QA4 A4-7 phase 3: an attested agent's card appends its own public key.
  const keyed = wire.agentCard(group, id, "python", "2026-01-01T00:00:00Z", "PT15M",
    "Researches a topic and writes a finding", ["research"],
    ["GoldenVectors$ResearchTask#v1"], ["GoldenVectors$Finding#v1"],
    { tokens: "low" }, { "GoldenVectors$ResearchTask#v1": "tasks" }, hex("agent_public_key_raw"));
  assert.deepEqual(dumps(keyed), hex("agent_card_with_key_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(keyed))), hex("agent_card_with_key_signature"));

  const spaceAd = wire.spaceAdvertisement(group, id.peerId, "tasks",
    "2026-01-01T00:00:00Z", "PT15M", ["GoldenVectors$ResearchTask#v1"],
    "LEASE_RACE", "ALLOWLIST", "TAG_SHARDED");
  assert.deepEqual(dumps(spaceAd), hex("space_ad_cbor"));
  assert.equal(deriveId(dumps(spaceAd)), GOLDEN["space_ad_space_id"]);
});

test("aggregate frames match Java, roster tokens as int64 (SPEC 8)", () => {
  const token = wire.rosterToken(GOLDEN["peer_id"]);
  assert.equal(typeof token, "bigint");
  assert.equal(token, BigInt(GOLDEN["aggregate_roster_token"]));
  assert.deepEqual(dumps(wire.aggregateShareFrame("golden", 4.5, 0.5)),
    hex("aggregate_share_frame_cbor"));
  assert.deepEqual(dumps(wire.aggregateExtremumFrame("golden", true, 4.5)),
    hex("aggregate_extremum_frame_cbor"));
  assert.deepEqual(dumps(wire.aggregateHistogramFrame("golden", 0.0, 10.0,
    [1.0, 0.0, 2.0, 0.5])), hex("aggregate_histogram_frame_cbor"));
  assert.deepEqual(dumps(wire.aggregateRosterFrame("golden", [token])),
    hex("aggregate_roster_frame_cbor"));

  // The decoded roster carries the token as a bigint, exactly.
  const roster = loads(hex("aggregate_roster_frame_cbor")) as Dict;
  const members = (roster["roster"] as Dict)["members"] as bigint[];
  assert.deepEqual(members, [token]);
  // Histogram buckets decode as CborDouble so they re-encode as float64.
  const histogram = loads(hex("aggregate_histogram_frame_cbor")) as Dict;
  const buckets = (histogram["histogram"] as Dict)["buckets"] as CborDouble[];
  assert.deepEqual(buckets.map((b) => b.value), [1.0, 0.0, 2.0, 0.5]);
  assert.ok(buckets.every((b) => b instanceof CborDouble));
});

test("gossip-learn exchanges match Java (SPEC 8)", () => {
  const model = wire.encodeModel([1.0, 2.5, -3.0]);
  assert.deepEqual(model, hex("learn_model_encoding"));
  assert.equal(wire.contentId(model), GOLDEN["learn_content_id"]);
  assert.deepEqual(dumps(wire.learnExchange("golden-model", 7, "OFFER", 2, model, null)),
    hex("learn_exchange_offer_cbor"));
  assert.deepEqual(dumps(wire.learnExchange("golden-model", 7, "ACCEPT", 3, model, null)),
    hex("learn_exchange_accept_cbor"));
  assert.deepEqual(dumps(wire.learnExchange("golden-model", 7, "BUSY", 0, null, null)),
    hex("learn_exchange_busy_cbor"));
  // int64 fields accept a bigint too, and encode identically when small.
  assert.deepEqual(dumps(wire.learnExchange("golden-model", 7n, "BUSY", 0n, null, null)),
    hex("learn_exchange_busy_cbor"));
});

test("int64 values beyond the safe range round-trip as BigInt", () => {
  const token = BigInt(GOLDEN["aggregate_roster_token"]);
  assert.deepEqual(dumps(token), Buffer.from("3b68e767e0853dc19a", "hex"));
  assert.equal(loads(Buffer.from("3b68e767e0853dc19a", "hex")), token);
  // Extremes of the 64-bit range, both signs, minimal width.
  const max = (1n << 64n) - 1n;
  assert.deepEqual(dumps(max), Buffer.from("1bffffffffffffffff", "hex"));
  assert.equal(loads(dumps(max)), max);
  const min = -(1n << 64n);
  assert.deepEqual(dumps(min), Buffer.from("3bffffffffffffffff", "hex"));
  assert.equal(loads(dumps(min)), min);
  assert.throws(() => dumps(max + 1n), RangeError);
  assert.throws(() => dumps(min - 1n), RangeError);
  // Inside the safe range a bigint is just an integer: same bytes as the
  // number, and it decodes back as a number.
  assert.deepEqual(dumps(7n), dumps(7));
  assert.deepEqual(dumps(-1n), dumps(-1));
  assert.equal(loads(dumps(7n)), 7);
  assert.equal(loads(Buffer.from("1b001fffffffffffff", "hex")), Number.MAX_SAFE_INTEGER);
  assert.equal(loads(Buffer.from("1b0020000000000000", "hex")), 2n ** 53n);
  // A non-integer number still needs the explicit double wrapper.
  assert.throws(() => dumps(4.5), TypeError);
});

test("joinByGroupId accepts only the verified founding document (SPEC 5.1, 10.1)", async () => {
  const group = GOLDEN["founding_group_id"];
  const peer = new Peer(identity(), group);
  const joined = peer.awaitFounding(group, 2_000);

  const genuine = wire.decodeFrame(hex("group_ad_frame_cbor"))!;
  assert.ok(peer.accepts(genuine), "a GROUP_AD for the wanted group passes the filter before membership");

  // Hostile answers on the wire: same envelope shape, adversarial bodies.
  const id = identity();
  for (const name of ["adv_group_ad_wrong_id_cbor", "adv_group_ad_forged_signature_cbor"]) {
    const env = wire.decodeFrame(wire.encodeFrame(wire.envelope(group, "GROUP_AD",
      id.peerId, GOLDEN["hlc_encoded"], hex(name), id.peerId), id))!;
    assert.ok(peer.accepts(env));
    assert.equal(peer.offerGroupAd(env), false, name);
  }
  // A genuine document for a different group than the one wanted is ignored too.
  const other = { ...genuine, group: GOLDEN["group_id"] };
  assert.equal(peer.offerGroupAd(other), false);
  // Wrong kind, garbage body: ignored without throwing.
  assert.equal(peer.offerGroupAd({ ...genuine, kind: "PING" }), false);
  assert.equal(peer.offerGroupAd({ ...genuine, body: new Uint8Array([0xff]) }), false);

  assert.equal(peer.offerGroupAd(genuine), true);
  const founding = await joined;
  assert.deepEqual(dumps(founding), hex("signed_group_ad_cbor"));
  assert.equal(peer.offerGroupAd(genuine), false, "nothing pending once joined");

  // Without a verified answer the join times out.
  await assert.rejects(new Peer(identity(), group).awaitFounding(group, 20), /timed out/);
});

test("every golden vector decodes", () => {
  const checked: string[] = [];
  for (const [name, value] of Object.entries(GOLDEN)) {
    // Deltas too, and the adv_* vectors: their content (not their encoding)
    // is hostile, so they round-trip like the rest. The deep-nesting vector
    // alone is undecodable by design (proven refused below).
    if ((name.endsWith("_cbor") || name.endsWith("_delta")) && name !== "adv_deep_nesting_cbor") {
      const raw = Buffer.from(value, "hex");
      const decoded = loads(raw);
      assert.notEqual(decoded, undefined);
      // Canonical form is a fixed point: re-encoding reproduces Java's exact
      // bytes for every vector (SPEC v0.1.8, definite-length arrays).
      assert.deepEqual(dumps(decoded), raw, name);
      checked.push(name);
    }
  }
  assert.ok(checked.includes("adv_agent_state_peer_key_delta")
    && checked.includes("adv_agent_state_wrong_signer_delta"), "the adversarial deltas round-trip");
});

// ---------------------------------------------------------------------------
// Adversarial conformance: every adv_* vector is a hostile input this client
// must reject — by failed decode, failed verification, or a bounds check —
// without crashing its reader. The same vectors gate the Java and Python
// implementations, so all three reject identically (security review §6 /
// remediation plan Workstream 1).

const HOSTILE_CLAIM_DELTAS = [
  "adv_claim_bad_signature_delta",
  "adv_claim_transplanted_delta",
  "adv_claim_nan_bid_delta",
  "adv_claim_epoch_zero_delta",
  "adv_claim_epoch_jump_delta",
  "adv_claim_eternal_delta",
];

test("hostile claims never enter the lattice", () => {
  for (const name of HOSTILE_CLAIM_DELTAS) {
    const peer = new Peer(identity(), GOLDEN["group_id"]);
    let delta: Dict;
    try {
      delta = loads(hex(name)) as Dict;
    } catch {
      continue; // rejected at decode (e.g. an unsafe uint64): equally refused
    }
    (peer as unknown as {
      foldClaim(entryId: string, signed: Dict): void;
    }).foldClaim(String(delta["claimEntry"]), delta["claim"] as Dict);
    const claims = (peer as unknown as { claims: Map<string, Dict> }).claims;
    assert.equal(claims.size, 0, name);
  }
});

test("deep nesting is refused bounded", () => {
  assert.throws(() => loads(hex("adv_deep_nesting_cbor")));
});

test("a tampered frame signature never verifies", () => {
  assert.equal(wire.decodeFrame(hex("adv_frame_bad_signature")), null);
});

test("a misaddressed frame fails the reader filter", () => {
  const env = wire.decodeFrame(hex("adv_frame_wrong_destination"));
  assert.notEqual(env, null); // the signature itself is valid
  assert.equal(env!["to"], GOLDEN["adv_frame_wrong_destination_to"]);
  // The reader honors an addressed frame only when it is the recipient: the
  // same signed PING addressed to us passes, the misaddressed one fails.
  const peer = new Peer(identity(), GOLDEN["group_id"]);
  assert.equal(peer.accepts(wire.decodeFrame(hex("ping_frame_cbor"))), true);
  assert.equal(peer.accepts(env), false);
});

test("a frame for a foreign group fails the reader filter", () => {
  // SPEC section 9: receivers reject envelopes whose group they do not belong to.
  const env = wire.decodeFrame(hex("ping_frame_cbor"));
  assert.equal(new Peer(identity(), GOLDEN["group_id"]).accepts(env), true);
  assert.equal(new Peer(identity(), "zSomeOtherGroup").accepts(env), false);
  assert.equal(new Peer(identity(), GOLDEN["group_id"]).accepts(null), false);
});

test("the frame cap matches the shared constant", () => {
  assert.equal(wire.MAX_FRAME_BYTES, Number(GOLDEN["max_frame_bytes"]));
});

test("the HLC is monotonic and merges observed stamps under the clamp", () => {
  const a = wire.hlcNow("hlc-test");
  const b = wire.hlcNow("hlc-test");
  assert.ok(wire.compareHlc(b, a) > 0, "same-millisecond stamps must not collide");

  // An observed remote stamp inside the skew window orders later stamps after it.
  const ahead = `${Date.now() + 5_000}:7:remote`;
  wire.hlcObserve("hlc-test", ahead);
  assert.ok(wire.compareHlc(wire.hlcNow("hlc-test"), ahead) > 0);

  // A far-future stamp is clamped away and cannot pin the clock (ASF-020).
  wire.hlcObserve("hlc-clamped", `${Date.now() + wire.MAX_HLC_SKEW_MILLIS + 60_000}:0:evil`);
  const next = Number(wire.hlcNow("hlc-clamped").split(":")[0]);
  assert.ok(next < Date.now() + wire.MAX_HLC_SKEW_MILLIS);
});

test("a replayed early state cannot roll back the joined view", () => {
  const newer: Dict = {
    adds: [{ replica: "r1", counter: 1 }, { replica: "r2", counter: 1 }],
    removes: [{ replica: "r1", counter: 1 }],
    leaseStamp: "200:0:r2", leaseValue: { holder: "r2/agent" }, completed: false,
  };
  const replayedInitial: Dict = {
    adds: [{ replica: "r1", counter: 1 }],
    removes: [],
    leaseStamp: "100:0:r1", leaseValue: { holder: "r1/agent" }, completed: false,
  };
  const merged = joinStates(newer, replayedInitial);
  assert.deepEqual(merged["removes"], [{ replica: "r1", counter: 1 }]);
  assert.equal((merged["adds"] as Dict[]).length, 2);
  assert.equal(merged["leaseStamp"], "200:0:r2");
  assert.deepEqual(merged["leaseValue"], { holder: "r2/agent" });

  // Completion is monotone through the join.
  const completed = joinStates({ ...newer, completed: true }, replayedInitial);
  assert.equal(completed["completed"], true);
});

// TECH-SPEC §7.2's two-key rule (QA4 A4-7): each hostile certificate delta
// decodes and differs from the certified golden delta in exactly one respect,
// and each is dropped before it reaches the joined view.
const HOSTILE_CERTIFICATE_DELTAS = [
  "adv_cert_wrong_peer_delta",
  "adv_cert_wrong_agent_delta",
  "adv_cert_expired_delta",
  "adv_cert_uncertified_key_delta",
  "adv_cert_peer_signed_record_delta",
];

function peerAt(iso: string): Peer {
  const nowMillis = parseInstantMillis(iso);
  return new Peer(identity(), GOLDEN["group_id"], () => nowMillis);
}

function foldState(peer: Peer, name: string): void {
  const delta = loads(hex(name)) as Dict;
  (peer as unknown as { fold(dto: Dict): void }).fold(delta["state"] as Dict);
}

test("hostile certificates never authenticate a record", () => {
  // v0.1.13: the control is the agent-signed delta (an attested entry's state
  // must be agent-signed).
  const control = peerAt(GOLDEN["certificate_verify_at"]);
  foldState(control, "delta_agent_signed_cbor");
  assert.equal(control.states.size, 1);
  for (const name of HOSTILE_CERTIFICATE_DELTAS) {
    const peer = peerAt(GOLDEN["certificate_verify_at"]);
    const state = (loads(hex(name)) as Dict)["state"] as Dict;
    assert.equal(typeof state["agentCertificate"], "object", name);
    foldState(peer, name);
    assert.equal(peer.states.size, 0, name);
  }
});

test("an expired certificate is refused whatever the receiver's clock (SPEC 4.2 v0.1.13)", () => {
  // Judged at the record's signing time: this certificate lapsed before the
  // record's stamp, so no receiver clock makes it authenticate.
  for (const at of ["2024-12-31T00:30:00Z", GOLDEN["certificate_verify_at"]]) {
    const peer = peerAt(at);
    foldState(peer, "adv_cert_expired_delta");
    assert.equal(peer.states.size, 0, at);
  }
});

test("an attested entry's state must be signed by its agent (SPEC 11a.4 A6)", () => {
  for (const name of ["adv_legacy_state_on_attested_entry_delta_cbor", "delta_with_certificate_cbor",
    "adv_agent_state_peer_key_delta", "adv_agent_state_wrong_signer_delta"]) {
    const peer = peerAt(GOLDEN["certificate_verify_at"]);
    foldState(peer, name);
    assert.equal(peer.states.size, 0, name);
  }
  const control = peerAt(GOLDEN["certificate_verify_at"]);
  foldState(control, "delta_agent_signed_cbor");
  assert.equal(control.states.size, 1);
});

test("a record sealed under epoch two names its epoch (SPEC 11a.1 v0.1.13)", () => {
  const record = loads(hex("entry_record_key_epoch_cbor")) as Dict;
  assert.equal(Number(record["keyEpoch"]), 2);
  assert.deepEqual(dumps(wire.signViewOf(record)), hex("sign_view_key_epoch_cbor"));
  assert.deepEqual(dumps(wire.signView(String(record["entryId"]), String(record["spaceId"]),
    String(record["type"]), record["payload"] as Uint8Array, String(record["issuer"]),
    String(record["issued"]), 2)), hex("sign_view_key_epoch_cbor"));
  assert.equal(wire.verifyRecord(record, identity().publicRaw, null, 0), true);
  const plain = ((loads(hex("entry_state_dto_cbor")) as Dict)["record"]) as Dict;
  assert.deepEqual(dumps(wire.signViewOf(plain)), hex("sign_view_cbor"));
});

test("a certificate can certify the agent's encryption key (SPEC 11a.2a v0.1.13)", () => {
  const certificate = loads(hex("agent_certificate_with_encryption_cbor")) as Dict;
  assert.deepEqual(Buffer.from(certificate["encryptionPublicKey"] as Uint8Array),
    hex("agent_encryption_public_key_raw"));
  assert.deepEqual(dumps(certificateBody(certificate)),
    hex("agent_certificate_with_encryption_unsigned_cbor"));
  assert.equal(verifyAgentCertificate(certificate, identity().publicRaw, identity().agent("python"),
    parseInstantMillis(GOLDEN["certificate_verify_at"])), true);
});

test("credential revocations from the agent's own peer apply the freeze rule (SPEC 5.6)", () => {
  const registry = new revocation.Registry(() => null, () => GOLDEN["group_id"]);
  const now = parseInstantMillis("2026-06-01T00:00:00Z");
  for (const kind of ["agent", "agent_key"]) {
    assert.equal(registry.accept(revocation.CREDENTIAL_STREAM,
      hex(`signed_credential_revocation_${kind}_cbor`), now), true, kind);
  }
  const issued = parseInstantMillis("2026-01-01T00:00:00Z");
  const agent = identity().agent("python");
  assert.equal(registry.refuses(agent, null, issued - 90 * 60 * 1000), false);
  assert.equal(registry.refuses(agent, null, issued - 30 * 60 * 1000), true);
  assert.equal(registry.refuses(agent, hex("agent_public_key_raw"), 0), true);
  assert.equal(registry.refuses(identity().agent("sibling"), null, issued), false);
  const stranger = Identity.generate();
  const ad = hex("credential_revocation_agent_cbor");
  assert.equal(new revocation.Registry(() => null, () => GOLDEN["group_id"]).acceptSigned(
    revocation.CREDENTIAL_STREAM, { adBytes: ad, publicKey: stranger.publicRaw,
      signature: stranger.sign(ad) }, now), false);
});

test("a card declares its actions and carries its certificate (SPEC 6.1 v0.1.13)", () => {
  const id = identity();
  const task = "GoldenVectors$ResearchTask#v1";
  const card = wire.agentCard(GOLDEN["group_id"], id, "python", GOLDEN["certificate_verify_at"],
    "PT15M", "Researches a topic and writes a finding", ["research"], [task],
    ["GoldenVectors$Finding#v1"], { tokens: "low" }, { [task]: "tasks" },
    hex("agent_public_key_raw"), [wire.cardAction("research",
      "Researches a topic and writes a finding", [task], ["GoldenVectors$Finding#v1"], "take",
      "tasks")], loads(hex("agent_certificate_cbor")) as Dict);
  assert.deepEqual(dumps(card), hex("agent_card_with_actions_cbor"));
  assert.deepEqual(Buffer.from(id.sign(dumps(card))), hex("agent_card_with_actions_signature"));
  assert.equal(Identity.verify(id.publicRaw, hex("epoch_commitment_cbor"),
    hex("epoch_proof_signature")), true);
});

// ---------------------------------------------------------------------------
// v0.1.13 transitions (audit item 10): agent-signed renew, cancel and complete,
// a record under a renewed certificate, and their hostile twins.

const ENTRY = "11111111-2222-3333-4444-555555555555";

function goldenAgent() {
  return identity().subordinate("python", GOLDEN["certificate_verify_at"], "PT24H",
    Identity.fromPkcs8(hex("agent_private_key_pkcs8")));
}

function stampAt(offsetMillis: number, logical = 0): string {
  return `${wire.hlcPhysical(GOLDEN["hlc_encoded"]) + offsetMillis}:${logical}:${GOLDEN["peer_id"]}`;
}

function peerAtMillis(nowMillis: number): Peer {
  return new Peer(identity(), GOLDEN["group_id"], () => nowMillis);
}

function foldClaimOf(peer: Peer, name: string): void {
  const delta = loads(hex(name)) as Dict;
  (peer as unknown as { foldClaim(entryId: string, signed: Dict): void })
    .foldClaim(String(delta["claimEntry"]), delta["claim"] as Dict);
}

test("agent-signed renew, cancel and complete match Java and fold (SPEC 11a.4 v0.1.13)", () => {
  const id = identity();
  const agent = goldenAgent();
  const python = id.agent("python");
  const adds: Dict[] = [{ replica: id.peerId, counter: 1 }];
  const t0 = wire.hlcPhysical(GOLDEN["hlc_encoded"]);
  const writeLease: Dict = { holder: python, expiresAtMillis: 1735693200000, kind: "WRITE" };
  const record = (loads(hex("entry_state_agent_signed_cbor")) as Dict)["record"] as Dict;
  const cases: Array<[string, Dict[], string, Dict, boolean, string]> = [
    ["renew", [], stampAt(60_000), { holder: python, expiresAtMillis: t0 + 7_200_000, kind: "WRITE" },
      false, stampAt(60_000, 1)],
    ["cancel", adds, GOLDEN["hlc_encoded"], writeLease, false, stampAt(120_000)],
    ["complete", [], GOLDEN["hlc_encoded"], writeLease, true, stampAt(180_000)],
  ];
  const claimProof = (loads(hex("claim_delta_with_certificate_cbor")) as Dict)["claim"] as Dict;
  for (const [name, removes, leaseStamp, leaseValue, completed, signedAt] of cases) {
    const view = wire.stateSignView(GOLDEN["space_id"], ENTRY, adds, removes, leaseStamp, leaseValue,
      completed, python, signedAt);
    assert.deepEqual(dumps(view), hex(`state_sign_view_agent_${name}_cbor`), name);
    const dto: Dict = { record, issuerPublicKey: id.publicRaw, adds, removes, leaseStamp, leaseValue,
      completed, stateSig: agent.sign(dumps(view)), agentCertificate: agent.certificate,
      stateCertificate: agent.certificate, signer: python, signedAt };
    assert.deepEqual(dumps(dto), hex(`entry_state_agent_${name}_cbor`), name);
    assert.deepEqual(dumps(completed ? { state: dto, claimEntry: ENTRY, claim: claimProof }
      : { state: dto, claimEntry: null, claim: null }), hex(`delta_agent_${name}_cbor`), name);

    const peer = peerAt(GOLDEN["certificate_verify_at"]);
    foldState(peer, "delta_agent_signed_cbor");
    if (completed) {
      foldClaimOf(peer, `delta_agent_${name}_cbor`);
    }
    foldState(peer, `delta_agent_${name}_cbor`);
    const held = peer.states.get(ENTRY)!;
    if (name === "renew") {
      assert.equal(held["leaseStamp"], stampAt(60_000));
      assert.equal(Number((held["leaseValue"] as Dict)["expiresAtMillis"]), t0 + 7_200_000);
    } else if (name === "cancel") {
      assert.deepEqual(dumps(held["removes"] as Dict[]), dumps(adds));
    } else {
      assert.equal(held["completed"], true);
      assert.deepEqual(dumps(held["stateCertificate"] as Dict), hex("agent_certificate_cbor"));
    }
  }
});

test("a completion without its claim is refused (SPEC 11a.4)", () => {
  const peer = peerAt(GOLDEN["certificate_verify_at"]);
  foldState(peer, "delta_agent_signed_cbor");
  foldState(peer, "delta_agent_complete_cbor"); // its claim is never folded
  assert.equal(peer.states.get(ENTRY)!["completed"], false);
});

test("a state signed outside its window or beyond the drift ceiling is refused (SPEC 4.2 v0.1.13)", () => {
  for (const [name, offset] of [["adv_agent_state_out_of_window_delta", -3_600_000],
    ["adv_agent_state_drift_delta", 600_000 + 60_000]] as Array<[string, number]>) {
    const state = (loads(hex(name)) as Dict)["state"] as Dict;
    assert.equal(state["signedAt"], stampAt(offset), name);
    const peer = peerAt(GOLDEN["certificate_verify_at"]);
    foldState(peer, name);
    assert.equal(peer.states.size, 0, name);
  }
  // The drift vector is inside the window: a receiver whose clock has caught up accepts it.
  const caughtUp = peerAtMillis(wire.hlcPhysical(GOLDEN["hlc_encoded"]) + 60_000);
  foldState(caughtUp, "adv_agent_state_drift_delta");
  assert.deepEqual([...caughtUp.states.keys()], [ENTRY]);
});

test("an out-of-window agent claim is refused (SPEC 4.2 v0.1.13)", () => {
  const delta = loads(hex("adv_claim_cert_out_of_window_delta")) as Dict;
  assert.equal(((delta["claim"] as Dict)["claim"] as Dict)["stamp"], stampAt(-3_600_000));
  assert.equal(wire.verifyClaimProof(delta["claim"] as Dict,
    parseInstantMillis(GOLDEN["certificate_verify_at"])), false);
  const peer = peerAt(GOLDEN["certificate_verify_at"]);
  foldClaimOf(peer, "adv_claim_cert_out_of_window_delta");
  assert.equal(peer.claims.size, 0);
  foldClaimOf(peer, "claim_delta_with_certificate_cbor");
  assert.deepEqual([...peer.claims.keys()], [ENTRY]);
});

test("a relabelled key epoch never verifies (SPEC 11a.1 v0.1.13)", () => {
  const relabelled = loads(hex("adv_key_epoch_relabelled_record_cbor")) as Dict;
  const genuine = loads(hex("entry_record_key_epoch_cbor")) as Dict;
  assert.equal(Number(relabelled["keyEpoch"]), 3);
  assert.deepEqual(dumps({ ...relabelled, keyEpoch: 2 }), hex("entry_record_key_epoch_cbor"));
  assert.equal(wire.verifyRecord(genuine, identity().publicRaw, null, 0), true);
  assert.equal(wire.verifyRecord(relabelled, identity().publicRaw, null, 0), false);
  const peer = peerAt(GOLDEN["certificate_verify_at"]);
  foldState(peer, "adv_key_epoch_relabelled_delta");
  assert.equal(peer.states.size, 0);
  foldState(peer, "delta_key_epoch_cbor");
  assert.equal(Number((peer.states.get(ENTRY)!["record"] as Dict)["keyEpoch"]), 2);
});

test("leaf and join-credential revocations need the founder (SPEC 5.6 v0.1.13)", () => {
  const now = parseInstantMillis("2026-06-01T00:00:00Z");
  const sha = (text: string) => createHash("sha256").update(text).digest();
  const expected: { [kind: string]: Dict } = {
    x509_leaf: { kind: "X509_LEAF", x509Issuer: "CN=golden-leaf,O=Bad Monkey", x509Serial: "0a1b2c3d",
      certificateFingerprint: sha("golden-leaf-der") },
    join_credential: { kind: "JOIN_CREDENTIAL", credentialHash: sha("golden-join-credential") },
  };
  const founded = new revocation.Registry(() => GOLDEN["peer_id"], () => GOLDEN["group_id"]);
  const stranger = new revocation.Registry(() => Identity.generate().peerId, () => GOLDEN["group_id"]);
  for (const [kind, target] of Object.entries(expected)) {
    const ad = loads(hex(`credential_revocation_${kind}_cbor`)) as Dict;
    assert.deepEqual(dumps(ad["target"] as Dict), dumps(target), kind);
    assert.equal(ad["id"], revocation.revocationId(GOLDEN["group_id"], target));
    assert.equal(ad["issuer"], GOLDEN["peer_id"]);
    const signed = hex(`signed_credential_revocation_${kind}_cbor`);
    assert.equal(founded.accept(revocation.CREDENTIAL_STREAM, signed, now), true, kind);
    assert.equal(stranger.accept(revocation.CREDENTIAL_STREAM, signed, now), false, kind);
  }
  assert.deepEqual([...founded.credentials.keys()].sort(), [
    "JOIN_CREDENTIAL:" + sha("golden-join-credential").toString("hex"),
    "X509_LEAF:" + sha("golden-leaf-der").toString("hex")]);
});

test("a cross-issuer revocation is refused (SPEC 5.6 v0.1.13)", () => {
  const signed = loads(hex("adv_credential_revocation_cross_issuer_cbor")) as Dict;
  const ad = loads(Buffer.from(signed["adBytes"] as Uint8Array)) as Dict;
  assert.equal(ad["issuer"], deriveId(hex("adv_forger_public_key_raw")));
  assert.equal((ad["target"] as Dict)["agent"], identity().agent("python"));
  assert.equal(Identity.verify(signed["publicKey"] as Uint8Array, signed["adBytes"] as Uint8Array,
    signed["signature"] as Uint8Array), true);
  const now = parseInstantMillis("2026-06-01T00:00:00Z");
  for (const founder of [GOLDEN["peer_id"], null]) {
    const registry = new revocation.Registry(() => founder, () => GOLDEN["group_id"]);
    assert.equal(registry.accept(revocation.CREDENTIAL_STREAM,
      hex("adv_credential_revocation_cross_issuer_cbor"), now), false);
    assert.equal(registry.refuses(identity().agent("python"), hex("agent_public_key_raw"), 0), false);
  }
});

test("a record under a renewed certificate matches Java and is judged at signing time (SPEC 4.2 v0.1.13)", () => {
  const id = identity();
  const verifyAt = parseInstantMillis(GOLDEN["certificate_verify_at"]);
  const signedAt = parseInstantMillis(GOLDEN["renewed_certificate_signed_at"]);
  let now = verifyAt;
  const agent = id.renewingSubordinate("python", "PT24H", Identity.fromPkcs8(hex("agent_private_key_pkcs8")),
    () => now);
  assert.deepEqual(dumps(agent.certificate), hex("agent_certificate_cbor"));
  now = verifyAt + 13 * 3600 * 1000;
  assert.equal(agent.renewIfDue(), true);
  now = signedAt;
  const renewed = agent.certificateCovering(signedAt)!;
  assert.deepEqual(dumps(renewed), hex("renewed_agent_certificate_cbor"));

  const python = id.agent("python");
  const stamp = `${signedAt}:0:${id.peerId}`;
  const stateStamp = `${signedAt}:1:${id.peerId}`;
  const entry = "44444444-5555-6666-7777-888888888888";
  const view = wire.signView(entry, GOLDEN["space_id"], "GoldenVectors$ResearchTask#v1",
    hex("task_payload_cbor"), python, stamp);
  assert.deepEqual(dumps(view), hex("sign_view_renewed_certificate_cbor"));
  const lease: Dict = { holder: python, expiresAtMillis: signedAt + 3_600_000, kind: "WRITE" };
  const record: Dict = { entryId: entry, spaceId: GOLDEN["space_id"], type: "GoldenVectors$ResearchTask#v1",
    payload: hex("task_payload_cbor"), payloadRef: null, issuer: python, issued: stamp, lease, tags: {},
    sig: agent.sign(dumps(view)) };
  const adds: Dict[] = [{ replica: id.peerId, counter: 21 }];
  const stateView = wire.stateSignView(GOLDEN["space_id"], entry, adds, [], stamp, lease, false, python,
    stateStamp);
  const dto: Dict = { record, issuerPublicKey: id.publicRaw, adds, removes: [], leaseStamp: stamp,
    leaseValue: lease, completed: false, stateSig: agent.sign(dumps(stateView)), agentCertificate: renewed,
    stateCertificate: renewed, signer: python, signedAt: stateStamp };
  assert.deepEqual(dumps(dto), hex("entry_state_renewed_certificate_cbor"));
  assert.deepEqual(dumps({ state: dto, claimEntry: null, claim: null }), hex("delta_renewed_certificate_cbor"));

  const longAfter = signedAt + 30 * 3600 * 1000;
  const first = loads(hex("agent_certificate_cbor")) as Dict;
  assert.equal(verifyAgentCertificateAt(renewed, id.publicRaw, python, signedAt, longAfter), true);
  assert.equal(verifyAgentCertificate(renewed, id.publicRaw, python, longAfter), false);
  assert.equal(verifyAgentCertificateAt(first, id.publicRaw, python, signedAt, signedAt), false);
  const peer = peerAtMillis(signedAt);
  foldState(peer, "delta_renewed_certificate_cbor");
  assert.deepEqual([...peer.states.keys()], [entry]);
  const behind = peerAt(GOLDEN["certificate_verify_at"]); // the stamp leads it beyond the drift ceiling
  foldState(behind, "delta_renewed_certificate_cbor");
  assert.equal(behind.states.size, 0);
});
